### ISSUE TITLE
Given the user inputs an address obtain geo coordinates from MapZen

### ISSUE THREAD

**Issue by sgimeno** [adab1ts/veinapp#4]
![veinapp - searching architecture - page 1](https://cloud.githubusercontent.com/assets/946661/22896476/85b6de4e-f220-11e6-8456-d8b4ef2ecd4b.png)

## Acceptance criteria

 - [ ] Markup for header
 - [ ] Input for address sends a request to MapZen
 - [ ] Geo coordinates are shown

**Comment by plastikaweb** [comment]
Given an input field the user can write an address and on sending a request (via Enter Key or clicking a send button) the system will obtain the corresponding coords if available using mapzen REST API.
If no result is obtained, it must be shown to the user.
If result is obtained it must be change the app state: 
```
ICurrentSearch = {
address: string, 
lat: number, 
long: number
}
```
Elements to develop: 
- Ngrx Store
- LocationService
- MapzenService
- TextSearchComponent + template + styles
